[package]
name = "crane"
version = "0.1.0"
authors = ["jianliangw1@gmail.com"]
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
pyo3 = "0.15"
log = "0.4.0"
env_logger = "0.9.0"
exitcode = "1.1.2"
